name: youprint
description: Text parser for ESC/POS Thermal Printer.
version: 1.0.3
homepage: https://github.com/youtaplibrary/youprint
publish_to: none

environment:
  sdk: '>=2.19.6 <3.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  image: 3.2.2
  zxing_lib: 1.0.0
  fluetooth:
    git:
      url: https://github.com/youtaplibrary/fluetooth.git
      ref: 0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0